# Generated by Django 3.0.5 on 2020-05-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60, null=True)),
                ('city', models.CharField(max_length=60)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=8)),
                ('farm', models.TextField()),
            ],
        ),
    ]
